services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file: .env
    # restart: on-failure
    networks:
      - db-net

  media:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - media-data:/var/www/media/uploads
      - ./media/defaults:/var/www/media/defaults:ro
      - ./media/media-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # restart: on-failure

  back:
    build: ./back/
    ports:
      - 3000:3000
    volumes:
      - media-data:/usr/src/app/uploads
    env_file: .env
    depends_on:
      db:
        condition: service_started
      media:
        condition: service_started
    networks:
      - db-net

  front:
    build: ./front/
    ports:
      - 80:80

volumes:
  db-data:
  media-data:

networks:
  db-net:
